# Generated by Django 2.1 on 2018-08-06 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuid', models.UUIDField(default=uuid.UUID('3f1641c8-4855-4e5a-b5ff-5807080aa9ac'))),
                ('titile', models.CharField(max_length=25, null=True, verbose_name='图片标题')),
                ('content', models.TextField(verbose_name='文章')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='图片发布者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iuid', models.UUIDField(default=uuid.UUID('50c03c35-b969-4834-917d-828a4282cf0d'))),
                ('titile', models.CharField(max_length=25, null=True, verbose_name='图片标题')),
                ('path', models.ImageField(default=None, upload_to='static/img', verbose_name='图片路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='图片发布者')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuid', models.UUIDField(default=uuid.UUID('faeb7ef3-7838-4d3c-9b9d-e8860a2cb5ce'))),
                ('titile', models.CharField(max_length=25, null=True, verbose_name='图片标题')),
                ('path', models.FileField(default=None, upload_to='static/video', verbose_name='图片路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='图片发布者')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'db_table': 'video',
            },
        ),
    ]
