# Generated by Django 2.1 on 2018-08-06 09:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='vuid',
            field=models.UUIDField(default=uuid.UUID('05111b9a-7f23-4eb7-88bd-6c1312888635')),
        ),
        migrations.AlterField(
            model_name='image',
            name='iuid',
            field=models.UUIDField(default=uuid.UUID('faa459cc-5168-4ebc-85d1-c2682ec92d21')),
        ),
        migrations.AlterField(
            model_name='video',
            name='vuid',
            field=models.UUIDField(default=uuid.UUID('59745b8f-1049-4411-aece-56df432709af')),
        ),
    ]
