# Generated by Django 2.1 on 2018-08-06 09:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20180806_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='vuid',
            field=models.UUIDField(default=uuid.UUID('8bf1875d-dafc-44f1-8167-fcc12cb3057f')),
        ),
        migrations.AlterField(
            model_name='image',
            name='iuid',
            field=models.UUIDField(default=uuid.UUID('3c4bd547-0231-4f02-9236-c10cd04c32c3')),
        ),
        migrations.AlterField(
            model_name='video',
            name='vuid',
            field=models.UUIDField(default=uuid.UUID('582a0682-8448-4c48-a076-7f18fd6f4a51')),
        ),
    ]
