# Generated by Django 2.1 on 2018-08-08 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20180806_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='vuid',
            field=models.UUIDField(default=uuid.UUID('7018ea49-6c35-4d0c-adae-52e654a352e7')),
        ),
        migrations.AlterField(
            model_name='image',
            name='iuid',
            field=models.UUIDField(default=uuid.UUID('404ec001-47e6-4db5-ac3c-0f163b83559d')),
        ),
        migrations.AlterField(
            model_name='video',
            name='vuid',
            field=models.UUIDField(default=uuid.UUID('c24ff0c2-414e-4c7d-b3a8-a24d43eea2f8')),
        ),
    ]
