# Generated by Django 2.1 on 2018-08-11 10:00

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0004_auto_20180808_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puid', models.UUIDField(default=uuid.UUID('b2f70f7a-fbed-4c71-b497-483fdab9092b'))),
                ('ptype', models.IntegerField(verbose_name='评论的类型')),
                ('fileuid', models.CharField(max_length=50, verbose_name='评论的文件')),
                ('contnet', models.CharField(max_length=150, verbose_name='评论的内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('commter', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL, verbose_name='评论的人')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='vuid',
            field=models.UUIDField(default=uuid.UUID('bde35dc8-6ccb-4de9-954f-28b201fc45cf')),
        ),
        migrations.AlterField(
            model_name='image',
            name='iuid',
            field=models.UUIDField(default=uuid.UUID('7ced11ea-f55a-44a7-8a2d-63d3d2ad8598')),
        ),
        migrations.AlterField(
            model_name='video',
            name='vuid',
            field=models.UUIDField(default=uuid.UUID('90189df3-1340-405f-ab0d-8f15ea51cd49')),
        ),
    ]
