# Generated by Django 2.1 on 2018-08-06 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.UUID('79961c0c-4761-42a5-96b3-14c94f299d94'), unique=True)),
                ('nick', models.CharField(max_length=25, verbose_name='昵称')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男'), (0, '女')], null=True, verbose_name='性别')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('status', models.IntegerField(choices=[(0, '未激活'), (1, '已激活'), (2, '封锁')], default=1, verbose_name='状态')),
                ('province', models.CharField(blank=True, max_length=12, null=True, verbose_name='省')),
                ('city', models.CharField(blank=True, max_length=12, null=True, verbose_name='市')),
                ('district', models.CharField(blank=True, max_length=12, null=True, verbose_name='区/县')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('login_ip', models.CharField(blank=True, max_length=15, null=True, verbose_name='登录 IP')),
                ('origin', models.CharField(blank=True, max_length=20, null=True, verbose_name='来源')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
