# Generated by Django 2.1 on 2018-08-06 09:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20180806_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('02d7c895-7631-42d2-98df-1a25fc3cbb99'), unique=True),
        ),
    ]
