# Generated by Django 2.1 on 2018-08-08 10:03

import django.contrib.auth.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20180806_0931'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('acc9c0f7-80e4-41fa-82c1-b0cc6830b3b7')),
        ),
    ]
